# Numpy 

In [107]:
import numpy as np

## Array Creation

In [148]:

arr1 = np.array([1,2,3,4]) #1d array
print(arr1)
print("-----------------")

arr2 = np.array([[1,2,3,4],[5,6,7,8]]) #2d array
print(arr2)
print("-----------------")

arr3 = np.array([[[1,2],[3,4],[5,6]]]) #3d array
print(arr3)
print("-----------------")

[1 2 3 4]
-----------------
[[1 2 3 4]
 [5 6 7 8]]
-----------------
[[[1 2]
  [3 4]
  [5 6]]]
-----------------


In [135]:
# Array of Zeros

zeros = np.zeros(5) #1d array of 5 zeros
zeros2D = np.zeros((3,4)) # 2d array of zeros , 3x4 size of array

#Array of Ones
ones = np.ones((2,3))
print(ones)

#Identity Array
print("======> Identity Array: ")
identity = np.eye(3)
print(identity)


#Random Value Array
print("======> Random Values Array: ")
identity = np.random.random((2,2))
print(identity)

[[1. 1. 1.]
 [1. 1. 1.]]
======> Identity Array: 
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
======> Random Values Array: 
[[0.73747862 0.12530841]
 [0.3501022  0.79504993]]


## Array Properties

In [137]:

arr = np.array([[1, 2, 3], [4, 5, 6]])

print("Array:", arr)
print("Shape:", arr.shape)      # Dimensions: (2, 3)
print("Number of dimensions:", arr.ndim)  # 2
print("Number of elements:", arr.size)    # 6
print("Data type:", arr.dtype)  # int64 (depends on system)

Array: [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Number of dimensions: 2
Number of elements: 6
Data type: int64


## Array Indexing and Slicing

In [139]:
arr = np.array([10, 20, 30, 40, 50])

print(arr[0])    # Output: 10 (first element)
print(arr[-1])   # Output: 50 (last element)
print(arr[1:4])  # Output: [20 30 40] (slicing)

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print(arr[0, 0])     # Output: 1 (row 0, column 0)
print(arr[1, 2])     # Output: 6 (row 1, column 2)
print(arr[0:2, 1:3]) # Output: [[2 3] [5 6]] (slicing)

10
50
[20 30 40]
1
6
[[2 3]
 [5 6]]


## Boolean Indexing:



arr = np.array([1, 2, 3, 4, 5, 6])

# Create a boolean mask
mask = arr > 3
print(mask)  # Output: [False False False True True True]

# Use the mask to filter elements
print(arr[mask])  # Output: [4 5 6]

# One-line version
print(arr[arr > 3])  # Output: [4 5 6]

## Array Operrations:

In [149]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)   # Output: [5 7 9] (Element-wise addition)
print(a - b)   # Output: [-3 -3 -3] (Subtraction)
print(a * b)   # Output: [4 10 18] (Multiplication)
print((a / b))   # Output: [0.25 0.4 0.5] (Division)
print(a ** 2)  # Output: [1 4 9] (Square)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


## Reshaping Arrays

In [150]:
arr = np.arange(12)  # [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

# Reshape to 3x4 matrix
reshaped = arr.reshape(3, 4)
print(reshaped)
# Output:
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

# Flatten back to 1D
flattened = reshaped.flatten()
print(flattened)  # Back to original

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [151]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [169]:
print(arr2d[:2,:3])

[[1 2 3]
 [4 5 6]]


## 4D Array

In [173]:
arr4D = np.ones((2,2,3,4)) 
# This means: 2 "outer" arrays, each containing 2 "middle" arrays,
# each containing 3 "inner" arrays, each containing 4 elements.